export const FollowActionType =  {
    ADD_FOLLOWING_USER: 'ADD_FOLLOWING_USER',
    DELETE_FOLLOWING_USER: 'DELETE_FOLLOWING_USER',
    GET_FOLLOWING_USERS: 'GET_FOLLOWING_USERS',
    SHOW_FOLLOWING_USER_LOADING: 'SHOW_FOLLOWING_USER_LOADING',
    HIDE_FOLLOWING_USER_LOADING: 'HIDE_FOLLOWING_USER_LOADING'
}
